### ISSUE TITLE
Refactor how the sidebar navigates to the results page

### ISSUE THREAD

**Issue by AvatarGreggles** [jandony/react-workout#18]
Maybe in the map function which returns the sidebar elements, we can wrap them in a Link? I tried but I then had to import the Router which got a bit messy.

**Comment by jandony** [comment]
I am going to include Restyling the sidebar to this Issue, because it's all the same component. I was thinking we could use a hamburger menu to open / close the sidebar. Only because it is impacting the muscle group cards on the page.

**Comment by AvatarGreggles** [comment]
Nice one! I actually asked a question in the PR about the routing, so maybe this answers it. But lets discuss in Slack, I'm eager to learn how it was done :)
