### ISSUE TITLE
Add a 3rd Tab for Your Workouts

### ISSUE THREAD

**Issue by jandony** [jandony/react-workout#8]

**Comment by AvatarGreggles** [comment]
Hey @jandony I picked this issue up, the PR is here: https://github.com/jandony/react-workout/pull/new/8-add-your-workouts-tab

I noticed we a Navbar component which wasn't being used, so I removed duplicate code and imported the Navbar to the app.

**Comment by jandony** [comment]
Sweet! Sounds good! Let me know if I need to merge anything.
